### ISSUE TITLE
request: Add a possibility to remove the artificial border.

### ISSUE THREAD

**Issue by FufferKS** [Betterment/alchemist#105]
### Is there an existing feature request for this?

- [X] I have searched the existing issues.

### Command

I would like a possibility to remove the artificial border

### Description

Hi, the FlutterGoldenTestAdapter adds an 8 pixel border inside FlutterGoldenTestAdapter.pumpGoldenTest. What is the reason for it, and how can I disable it?

![Screenshot 2023-11-21 at 12 06 45](https://github.com/Betterment/alchemist/assets/23334356/d2b7885e-aced-419d-8e91-9841d9e3c90c)

### Reasoning

This would be useful, because I want my goldens matching my app as close as possible.

**Comment by maxmitz** [comment]
I use my goldens as store screenshots and had the same issue. I created [a branch](https://github.com/maxmitz/alchemist_no_screenshot_padding) where I only set the padding to 0. If I find the time, I want to create a proper PR.
