### ISSUE TITLE
request: mock network images

### ISSUE THREAD

**Issue by VincentJouanne** [Betterment/alchemist#44]
### Is there an existing feature request for this?

- [X] I have searched the existing issues.

### Command
I would love to be able to mock network images in my tests

### Description

As a developer, I would love to be able to mock network images in my tests but it seems like it is not yet possible with Alchemist or is there any way to do so ? 

### Reasoning

I tried to make pass a golden test with a NetworkImage widget used in it but I have an infinite loading test.

### Additional context and comments

I found [a similar issue](https://github.com/Betterment/alchemist/issues/18) but I did not find any response in it.

Does the library supports today network image mocking ? 

Thanks a lot for this amazing package :)

**Comment by definitelyokay** [comment]
Hi! Thanks for opening an issue. I believe the general consensus was to let developers use whatever package they wished for to mock network images.

Here's an example from Alchemist that uses [mocktail_image_network](https://pub.dev/packages/mocktail_image_network):

https://github.com/Betterment/alchemist/blob/a1c042cac2087326e90b4df74082e0ad12e90bf6/test/smoke_tests/network_image_smoke_test.dart#L11-L14

**Comment by VincentJouanne** [comment]
Hi ! 
Oh I did not see this test before, thanks a lot for your reply, I tried it on my codebase and it works as expected :) 

Thanks a lot for your help !
