### ISSUE TITLE
Localization support

### ISSUE THREAD

**Issue by t-girniak** [Betterment/alchemist#49]
### Is there an existing feature request for this?

- [X] I have searched the existing issues.

### Command

It would be awesome to add a support for the localisation in the library

### Description

First of all, thanks for an awesome library and your work!

The problem is, I haven't found a proper way to add localisations delegate to the golden test, and this feature is extremely important to have in order to test any widget with localisation.

I've added localizationsDelegates param in my fork to enable localisation, and it actually worked. But the problem is, after adding an `AppLocalizationDelegate` to the `MaterialApp`, alchemist has stopped rendering any kind of images. Any asset or file image would become transparent. However, after removing the delegate, images appear again. I've tested adding the same `AppLocalizationDelegate` to the MaterialApp with a golden_toolkit library, and there was no such problem (images were rendered and localisation worked as well).

Maybe you have any ideas on how to add a localizationsDelegates to the test in a way that prevents this issue with rendering images?  

### Reasoning

I think that supporting localisation in the library would greatly increase the usability

### Additional context and comments

You can refer to my closed PR, where I've added the coreWrapper: https://github.com/Betterment/alchemist/pull/43

**Comment by t-girniak** [comment]
I've tried running your exact test but with Image.asset() and Image.file() widgets along with a text - the image is not rendered if I pass your `FakeLocalizationsDelegate` to delegates list. The same happens If I pass real delegate but not the fake one.

However, after I removed the `FakeLocalizationsDelegate` from delegates list - image rendered normally. The problem with localisation in the library is that it can not be combined with images right now.

Try running your asset_image_smoke_test but with `Localizations` widget as a wrapper in the builder: https://github.com/Betterment/alchemist/blob/main/test/smoke_tests/asset_image_smoke_test.dart

```
  goldenTest(
    'succeeds with an asset image',
    fileName: 'asset_image_smoke_test',
    pumpBeforeTest: precacheImages,
    builder: () => Localizations(
      locale: const Locale('en'),
      delegates: const [
        DefaultWidgetsLocalizations.delegate,
        FakeLocalizationsDelegate(),
      ],
      child: DefaultAssetBundle(
        bundle: FakeTestAssetBundle(),
        child: Image.asset('test.png'),
      ),
    ),
  );

```
It won't render the red square 🟥  :
![image](https://user-images.githubusercontent.com/33135135/167817085-e1c21544-0842-4cd4-8690-3d967aec7eb3.png)


But if you run the same test as above but without `FakeLocalizationsDelegate()` - it will render the red square in golden:

```
  goldenTest(
    'succeeds with an asset image',
    fileName: 'asset_image_smoke_test',
    pumpBeforeTest: precacheImages,
    builder: () => Localizations(
      locale: const Locale('en'),
      delegates: const [
        DefaultWidgetsLocalizations.delegate,
      ],
      child: DefaultAssetBundle(
        bundle: FakeTestAssetBundle(),
        child: Image.asset('test.png'),
      ),
    ),
  );

```
![image](https://user-images.githubusercontent.com/33135135/167817228-94d135f0-b41e-4bce-bb12-936931aff93a.png)

These tests were run on alchemist v0.3.3

**Comment by Kirpal** [comment]
Oh I see, sorry I misinterpreted your issue. Looks like this is being caused by the `FakeLocalizationsDelegate` loading asynchronously. I was able to get it working in two possible ways:
1. in the `FakeLocalizationsDelegate`, make `load` return synchronously:
*(This may not be desired if you're using your app's actual Localizations)*
```dart
Future<FakeLocalizations> load(Locale locale) => SynchronousFuture(FakeLocalizations());
```
3. add an extra `pump` to the `pumpBeforeTest` so it loads the strings before caching the images:
```dart
pumpBeforeTest: (tester) async {
  await pumpOnce(tester);
  await precacheImages(tester);
}
```
Let me know if this solves your issue!

**Comment by t-girniak** [comment]
Thanks for your help @Kirpal! It actually solved my issue!

This extra pump actually resolved the issue for me, and I was testing with real localisation, not the fake one :)
It worked out even without making load() synchronous, all thanks to adding `await pumpOnce(tester);`

I am not 100% sure that this workaround will resolve all of the similar cases, but maybe `await pumpOnce(tester);` should be added to the `precacheImages` function directly to prevent this bug? It's not really obvious, and there may be others straggling with this kind of issue.

**Comment by Kirpal** [comment]
I'm conflicted about adding it to precache images because it might be unexpected in some cases (while necessary in cases like this). I lean more on the side of not including it because that allows for more precise control of the rendering. If it were to be included in `precacheImages` it might cause issues with animations for example, and then a user would need to create a copy of `precacheImages` without the pump to get the rendering they want.

I do think it's probably worth documenting this somewhere though because this case will happen in other widgets with similar rendering behavior to Localizations(deferring the first frame).

**Comment by t-girniak** [comment]
Yes, I agree with you. But it is worth documenting this case for sure then. Thanks a lot for your help Kirpal! 
I am closing the issue for now.
