### ISSUE TITLE
request: add a Flutter application example

### ISSUE THREAD

**Issue by alestiago** [Betterment/alchemist#56]
### Is there an existing feature request for this?

- [X] I have searched the existing issues.

### Command

Add a Flutter application example.

### Description

Instead of a plain markdown file (https://github.com/Betterment/alchemist/blob/main/example/example.md), it would be great to have a real Flutter example application.

It would be ideal if this example showcased the functionality Alchemist provides. For example, showing a login page with goldens for different languages with a custom font.

### Reasoning

- Makes it easier for other developers to pick up the package.
- Allows catching issues from the example (eg #55).
- Easily allow testing changes (while developing) against a real codebase

**Comment by jeroen-meijer** [comment]
Example project has been built in my fork [here](https://github.com/jeroen-meijer/alchemist/tree/feat/example-project).

Note that the included goldens will need to be regenerated once #55 is merged.
