### ISSUE TITLE
fix: missing implementation of BlockedTextCanvasAdapter.restoreToCount

### ISSUE THREAD

**Issue by arturplaczek** [Betterment/alchemist#83]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Version

3.4.0-34.1.pre

### Description

After upgrade flutter to beta (3.4.0-34.1.pre) I recive

```
 Error: The non-abstract class 'BlockedTextCanvasAdapter' is missing implementations for these members:
 - Canvas.restoreToCount
Try to either
 - provide an implementation,
 - inherit an implementation from a superclass or mixin,
 - mark the class as abstract, or
 - provide a 'noSuchMethod' implementation.
```
on
```
class BlockedTextCanvasAdapter implements Canvas {
```

### Steps to reproduce

1. Setup new project
2. Add alchemist
3. Prepare simple test
4. Run test

### Expected behavior

Adding to the `BlockedTextCanvasAdapter` 
method `void restoreToCount(int count) => parent.restoreToCount(count);`

### Screenshots

<img width="996" alt="CleanShot 2022-11-14 at 14 16 34@2x" src="https://user-images.githubusercontent.com/33895544/201669752-98cd35ed-8e71-464e-abe6-9199993b71da.png">

**Comment by Kirpal** [comment]
Should be fixed in #84!
