### ISSUE TITLE
fix: Flutter 3.13.1 - Custom RenderObjects are not visible anymore on golden images

### ISSUE THREAD

**Issue by karvulf** [Betterment/alchemist#97]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Version

0.6.1

### Description

When updating to the newest flutter version `3.13.1`, the golden tests are failing when widgets with custom RenderObjects are tested. 
Previously the text and icons were visible in the golden images. Now nothing is displayed (see the screenshots).

### Steps to reproduce

```dart
import 'package:alchemist/alchemist.dart';
import 'package:flutter/material.dart';

void main() {
// ignore: discarded_futures,
  goldenTest(
    'golden test',
    fileName: 'h4u_adaptive_text',
    builder: () => const SizedBox(
      height: 800,
      width: 400,
      child: CustomExampleRenderObject(),
    ),
  );
}

class CustomExampleRenderObject extends LeafRenderObjectWidget {
  const CustomExampleRenderObject({super.key});

  @override
  CustomExampleRenderBox createRenderObject(BuildContext context) {
    return CustomExampleRenderBox();
  }
}

class CustomExampleRenderBox extends RenderBox {
  @override
  void paint(PaintingContext context, Offset offset) {
    final canvas = context.canvas;
    canvas.save();
    canvas.translate(offset.dx, offset.dy);

    final textPainter = TextPainter(
      text: const TextSpan(
        text: 'text',
        style: TextStyle(),
      ),
      textDirection: TextDirection.ltr,
    );
    textPainter.layout();
    textPainter.paint(canvas, Offset.zero);

    canvas.restore();
  }

  @override
  void performLayout() {
    this.size = this.computeDryLayout(this.constraints);
  }

  @override
  Size computeDryLayout(BoxConstraints constraints) {
    return constraints.constrain(Size(
      200.0,
      constraints.maxHeight,
    ));
  }
}

```

### Expected behavior

In the example, I would expect that my text is still shown in the images and in general I would expect that it still works with Custom RenderObjects.

### Screenshots

CI Image with Flutter Version `3.10.6`:
<img width="428" alt="Bildschirmfoto 2023-08-30 um 07 42 26" src="https://github.com/Betterment/alchemist/assets/36191072/d328a397-0dae-4a33-970d-1d6c7fbc88a9">

CI Image with Flutter Version `3.13.1`:
![Bildschirmfoto 2023-08-30 um 07 30 30](https://github.com/Betterment/alchemist/assets/36191072/4d8a6907-64e8-40b7-8971-e9e4ee0c8117)

**Comment by timokz** [comment]
Can reproduce with similar conditions.
Until #95 is merged, you will need to revert your projects sdk, as I have done

**Comment by karvulf** [comment]
When I testet it with the pr the issue still remained @timokz

**Comment by timokz** [comment]
> When I testet it with the pr the issue still remained @timokz 

Well that's really bad 😅

**Comment by timokz** [comment]
Can you confirm encountering the same error? @karvulf 

```
/Pub/Cache/hosted/pub.dev/alchemist-0.6.1/lib/src/golden_test_adapter.dart:53:38: Error: A value of type 'void Function(String, Future<void> Function(WidgetTester), {int? retry, bool semanticsEnabled, bool? skip, dynamic tags, Timeout? timeout, TestVariant<Object?> variant})' can't be assigned to a variable of type 'FutureOr<void> Function(String, Future<void> Function(WidgetTester), {Duration? initialTimeout, bool semanticsEnabled, bool? skip, dynamic tags, Timeout? timeout, TestVariant<Object?> variant})'.
 - 'Future' is from 'dart:async'.
 - 'WidgetTester' is from 'package:flutter_test/src/widget_tester.dart' ('/timok/fvm/versions/3.13.0/packages/flutter_test/lib/src/widget_tester.dart').
 - 'Timeout' is from 'package:test_api/src/backend/configuration/timeout.dart' ('/timok/AppData/Local/Pub/Cache/hosted/pub.dev/test_api-0.6.0/lib/src/backend/configuration/timeout.dart').
 - 'TestVariant' is from 'package:flutter_test/src/widget_tester.dart' ('/timok/fvm/versions/3.13.0/packages/flutter_test/lib/src/widget_tester.dart').
 - 'Object' is from 'dart:core'.
 - 'Duration' is from 'dart:core'.
TestWidgetsFn defaultTestWidgetsFn = testWidgets;
```

**Comment by karvulf** [comment]
I get no warnings or errors because of the version.
It's just the output of images from the golden test that are inconsistent to the flutter version`3.10.6`. Widgets that are CustomRenderBoxes are not rendered or showed in the output image (like above shown). @timokz
Or do you see the widget on the image when trying to run the golden test with it?
